parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: e100_dev
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: b2ca7bf50dcdc1cfd1a46abacaa24f5cd63e54a5
    database_path: null
